name: Publish to JSR
on:
  release:
    types: [published]

jobs:
  jsr-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - name: Publish package
        run: npx jsr publish
